baseURL = "https://www.jamilghar.com/"
languageCode = "en"
DefaultContentLanguage = "en"
title = " The Jamil Ghar"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-188548284-1"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
disableThemeSwitcher = true # Theme switcher is enabled by default
displayMode = "light"
#title = "The Jamil Ghar"
#author = "Tressa Jamil"
#copyright = "2020-2021"
description = "Our world needs more meals around the table. Have a seat at ours."
profilePicture = "images/profile_pic.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["recipe"]
images = ["images/site-feature-image.jpg"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.

[[params.socialIcons]]
#icon = "fab fa-instagram"
#title = "instagram"
#url = "https://www.instagram.com/thejamilghar"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:thejamilghar@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Recipes"
  weight = 200
  identifier = "recipes"
  url = "/recipe/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

##  [[menu.main]]
##  name = "Contact"
##  weight = 400
##  identifier = "contact"
##  url = "/contact/"
